"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import ThemeProvider from "@/theme";
import { Container, Box } from "@mui/material";
import Navbar from "@/UI/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Products Catalog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <Box>
            <Navbar />
            <Container>{children}</Container>
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
